export const AgentVids = {
  Gekko: "https://www.youtube.com/embed/iYFh_XAXSPk?mute=1",
  Harbor: "https://www.youtube.com/embed/qRao6FARFRo?mute=1",
  Neon: "https://www.youtube.com/embed/dtx8CgjRmqE?mute=1",
  Kayo: "https://www.youtube.com/embed/eU1l7eBy2_Y?mute=1",
  Chamber: "https://www.youtube.com/embed/FUoqAn5T4h4?mute=1",
  Killjoy: "https://www.youtube.com/embed/ua-iIRQDY8g?mute=1",
  Skye: "https://www.youtube.com/embed/C3QTyMXi-WE?mute=1",
  Deadlock: "https://www.youtube.com/embed/UK7Tdob8HQw?mute=1",
  Yoru: "https://www.youtube.com/embed/GdOEQv-zQVw?mute=1",
  Astra: "https://www.youtube.com/embed/-ylVnuPWlJM?mute=1",
  Reyna: "https://www.youtube.com/embed/IzsQNYrq9AM?mute=1",
  Viper: "https://www.youtube.com/embed/Yyu0YVZCmes?mute=1",
  Fade: "https://www.youtube.com/embed/UMzKD73cs3c?mute=1",
  Jett: "https://www.youtube.com/embed/xU2U73Tk-DM?mute=1",
  Phoenix: "https://www.youtube.com/embed/e_E9W2vsRbQ?mute=1",
  Raze: "https://www.youtube.com/embed/ZGvz7jTVbc8?mute=1",
  Brimstone: "https://www.youtube.com/embed/7yHnJ_oNxTI?mute=1",
  Omen: "https://www.youtube.com/embed/_jJdWy6bDj4?mute=1",
  Breach: "https://www.youtube.com/embed/Rux0HjzKQbw?mute=1",
  Sova: "https://www.youtube.com/embed/cSO109-TYJc?mute=1",
  Sage: "https://www.youtube.com/embed/j8T-pUsslws?mute=1",
};
export const Vids = ["https://www.youtube.com/embed/ygg148GTK_k?mute=1"];
